services:
  bot:
    image: ghcr.io/carlos0934/tg-replier:latest
    container_name: tg-replier
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      DATA_DIR: /app/data
    volumes:
      - tg-replier-data:/app/data
    init: true

volumes:
  tg-replier-data:
